### ISSUE TITLE
Sass interpolation wrapping a sass function seems to be unsupported

### ISSUE THREAD

**Issue by arondius** [tonyganch/gonzales-pe#256]
Sass interpolation wrapping a sass function seems to be unsupported:

The following rule will give me an error in atom:
.selector {
    width: calc(33.333333% - #{margin-padding(1)});
}

When Sass interpolation is wrapping a variable everything works as expected:
.selector {
    width: calc(33.333333% - #{$font-size});
}

Unsupported beautification result 'Parsing error: Please check the validity of the block starting from line #2
1 | .selector {
2*|     width: calc(33.333333% - #{margin-padding(1)});
3 | }
Gonzales PE version: 3.0.0-28
Syntax: scss'.
Hide Stack Trace
Error: Unsupported beautification result 'Parsing error: Please check the validity of the block starting from line #2
1 | .selector {
2*|     width: calc(33.333333% - #{margin-padding(1)});
3 | }
Gonzales PE version: 3.0.0-28
Syntax: scss'.
    at beautifyCompleted (/Users/arend/.atom/packages/atom-beautify/src/beautify.coffee:135:21)
    at tryCatcher (/Users/arend/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/arend/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/arend/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/arend/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/arend/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/Users/arend/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/arend/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/Users/arend/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)

**Comment by bgriffith** [comment]
This has been fixed for a while but also works in the latest release `v4.1.1`
