### ISSUE TITLE
Does not work with examples from README

### ISSUE THREAD

**Issue by varya** [tonyganch/gonzales-pe#33]
https://github.com/varya/gonzales-try/commit/48d20b3a968fb2d6d2528f1f838953fd35d48103

Output:

```
$ node test.js

/Users/varya/WebDev/SC5/gonzales-try/test.js:5
console.log(gonzales.cssToAST(css));
                     ^
TypeError: Object #<Object> has no method 'cssToAST'
    at Object.<anonymous> (/Users/varya/WebDev/SC5/gonzales-try/test.js:5:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

`golzales-pe` is installed locally

**Comment by tonyganch** [comment]
README is written for stable version, `3.0.0-10` is not documented yet because it'll change a lot later.
