### ISSUE TITLE
[sass] Declaration is parsed as a ruleset

### ISSUE THREAD

**Issue by tonyganch** [tonyganch/gonzales-pe#62]
From https://github.com/csscomb/csscomb.js/issues/333

```
» cat test.sass
.page-sidebar
  background #ccc

» csscomb -v  -l test.sass
stack:  TypeError: Cannot read property '0' of undefined
    at module.exports.process (/usr/local/lib/node_modules/csscomb/lib/options/eof-newline.js:16:26)
    at /usr/local/lib/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:206:21
    at Array.forEach (native)
    at processNode (/usr/local/lib/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:202:14)
    at /usr/local/lib/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:189:13
```

`background #ccc` is getting parsed as a ruleset with selector only, no block

**Comment by tonyganch** [comment]
@leonko, why is there no `:` between `background` and `#ccc`?

**Comment by batizhevsky** [comment]
yes, my mistake.
Thank you for maintaining and development great product!
