### ISSUE TITLE
[SASS] multiple selectors in new lines

### ISSUE THREAD

**Issue by batizhevsky** [tonyganch/gonzales-pe#65]
```
a,
li,
p
  color: red
```

output:

```
{
  "type": "stylesheet",
  "content": [
    {
      "type": "ruleset",
      "content": [
        {
          "type": "selector",
          "content": [
            {
              "type": "simpleSelector",
              "content": [
                {
                  "type": "ident",
                  "content": "a",
                  "start": {
                    "line": 1,
                    "column": 1
                  }
                }
              ],
              "start": {
                "line": 1,
                "column": 1
              }
            },
            {
              "type": "delimiter",
              "content": ",",
              "start": {
                "line": 1,
                "column": 2
              }
            },
            {
              "type": "space",
              "content": "\n",
              "start": {
                "line": 1,
                "column": 3
              }
            },
            {
              "type": "simpleSelector",
              "content": [
                {
                  "type": "ident",
                  "content": "li",
                  "start": {
                    "line": 2,
                    "column": 1
                  }
                }
              ],
              "start": {
                "line": 2,
                "column": 1
              }
            }
          ],
          "start": {
            "line": 1,
            "column": 1
          }
        },
        {
          "type": "selector",
          "content": [
            {
              "type": "delimiter",
              "content": ",",
              "start": {
                "line": 2,
                "column": 3
              }
            },
            {
              "type": "space",
              "content": "\n",
              "start": {
                "line": 2,
                "column": 4
              }
            },
            {
              "type": "simpleSelector",
              "content": [
                {
                  "type": "ident",
                  "content": "p",
                  "start": {
                    "line": 3,
                    "column": 1
                  }
                },
                {
                  "type": "space",
                  "content": "\n",
                  "start": {
                    "line": 3,
                    "column": 2
                  }
                }
              ],
              "start": {
                "line": 3,
                "column": 1
              }
            }
          ],
          "start": {
            "line": 2,
            "column": 3
          }
        },
        {
          "type": "block",
          "content": [
            {
              "type": "space",
              "content": "  ",
              "start": {
                "line": 4,
                "column": 1
              }
            },
            {
              "type": "declaration",
              "content": [
                {
                  "type": "property",
                  "content": [
                    {
                      "type": "ident",
                      "content": "color",
                      "start": {
                        "line": 4,
                        "column": 3
                      }
                    }
                  ],
                  "start": {
                    "line": 4,
                    "column": 3
                  }
                },
                {
                  "type": "propertyDelimiter",
                  "content": ":",
                  "start": {
                    "line": 4,
                    "column": 8
                  }
                },
                {
                  "type": "space",
                  "content": " ",
                  "start": {
                    "line": 4,
                    "column": 9
                  }
                },
                {
                  "type": "value",
                  "content": [
                    {
                      "type": "ident",
                      "content": "red",
                      "start": {
                        "line": 4,
                        "column": 10
                      }
                    }
                  ],
                  "start": {
                    "line": 4,
                    "column": 10
                  }
                }
              ],
              "start": {
                "line": 4,
                "column": 3
              }
            },
            {
              "type": "declarationDelimiter",
              "content": "\n",
              "start": {
                "line": 4,
                "column": 13
              }
            }
          ],
          "start": {
            "line": 4,
            "column": 1
          }
        }
      ],
      "start": {
        "line": 1,
        "column": 1
      }
    }
  ],
  "start": {
    "line": 1,
    "column": 1
  }
}
```

As you can see, parser break last selector in separate group.

As result csscomb breaks on this example:

```
stack:  TypeError: Cannot read property 'length' of undefined
    at module.exports.process (/Users/Leonid/Development/OSS/csscomb.js/lib/options/space-before-selector-delimiter.js:33:42)
    at /Users/Leonid/Development/OSS/csscomb.js/node_modules/csscomb-core/lib/core.js:206:21
    at Array.forEach (native)
    at processNode (/Users/Leonid/Development/OSS/csscomb.js/node_modules/csscomb-core/lib/core.js:202:14)
    at /Users/Leonid/Development/OSS/csscomb.js/node_modules/csscomb-core/lib/core.js:211:13
    at Array.forEach (native)
    at processNode (/Users/Leonid/Development/OSS/csscomb.js/node_modules/csscomb-core/lib/core.js:202:14)
    at /Users/Leonid/Development/OSS/csscomb.js/node_modules/csscomb-core/lib/core.js:211:13
    at Array.forEach (native)
    at processNode (/Users/Leonid/Development/OSS/csscomb.js/node_modules/csscomb-core/lib/core.js:202:14)
```

**Comment by tonyganch** [comment]
Fixed in `dev`
