### ISSUE TITLE
Sass: comments after commas

### ISSUE THREAD

**Issue by minamarkham** [tonyganch/gonzales-pe#88]
in [Sass Lint](https://github.com/sasstools/sass-lint)

```
@if variable-exists(fonts) {
  @each $font-face in $fonts {
    @font-face {
      font-family: $font-face;
      src: url('font/#{$font-face}.eot'); // IE9 Compat Modes
      src: url('font/#{$font-face}.eot?#iefix') format('embedded-opentype'), // IE6-IE8
           url('font/#{$font-face}.woff') format('woff'), // Modern Browsers
           url('font/#{$font-face}.ttf') format('truetype'), // Safari, Android, iOS
           url('font/#{$font-face}.svg##{$font-face}') format('svg'); // Legacy iOS
      font-style: normal;
      font-weight: normal;
    }
  }
}
```

throw error

```
/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/lib/groot.js:21
    throw new Error('Parsing error' + fileInfo + ': ' + e.message);
          ^
Error: Parsing error at src/utilities/_fonts.scss: Please check validity of the block starting from line #15
    at module.exports (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/lib/groot.js:21:11)
    at Function.sassLint.lintText (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/sass-lint/index.js:43:13)
    at DestroyableTransform._transform (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/index.js:32:27)
    at DestroyableTransform.Transform._read (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:326:12)
    at writeOrBuffer (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:312:5)
    at DestroyableTransform.Writable.write (/Users/minamarkham/fooBar/node_modules/gulp-sass-lint/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:239:11)
    at write (/Users/minamarkham/fooBar/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/minamarkham/fooBar/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
```

Removing the comments resolves the error.

**Comment by tonyganch** [comment]
@minamarkham, what version of gonzales do you use?

**Comment by minamarkham** [comment]
Per Sass Lint's [package.json](https://github.com/sasstools/sass-lint/blob/master/package.json)

"gonzales-pe": "^3.0.0-31"

+@snugug

**Comment by tonyganch** [comment]
Fixed in `dev` :cherries: 
I'm not closing the issue to make sure later if the fix is needed for other syntaxes as well.

**Comment by Snugug** [comment]
Thanks Tony! Once a new release is rolled I'll roll it in.
